name: "Gotify"
description: "Secure local message Server"
version: "1.0.0"
url: "https://github.com/SmartLiving-Rocks/Gotify/"
panel_icon: mdi:cat
panel_title: Gotify
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  80/tcp: 80
